name: MakeCode
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: MakeCode screenshot
      uses: microsoft/pxt-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
